name: Test WIF Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to test in (optional)'
        type: choice
        options:
          - dev
          - staging
          - prod
      pool_id_suffix:
        description: 'Suffix for the Workload Identity Pool ID'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      issuer_uri:
        description: 'OIDC Issuer URI'
        required: true
        type: string
