name: Test WIF Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to test in'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      pool_id_suffix:
        description: 'Suffix for the Workload Identity Pool ID'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      issuer_uri:
        description: 'OIDC Issuer URI'
        required: true
        type: string

jobs:
  test_wif:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Optional

    - name: Test WIF Creation (Dry Run)
      run: |
        ENVIRONMENT="${{ github.event.inputs.environment }}"
        POOL_ID_SUFFIX="${{ github.event.inputs.pool_id_suffix }}"
        ISSUER_URI="${{ github.event.inputs.issuer_uri }}"
        BASE_POOL_ID="my-wif-pool"
        FULL_POOL_ID="${BASE_POOL_ID}-${POOL_ID_SUFFIX}"
        PROVIDER_ID="my-oidc-provider-${POOL_ID_SUFFIX}"

        echo "Testing in ${ENVIRONMENT} environment..."
        echo "Using Pool ID Suffix: ${POOL_ID_SUFFIX}"
        echo "Using Issuer URI: ${ISSUER_URI}"
        echo "Full Pool ID will be: ${FULL_POOL_ID}"

        echo "--- Dry Run: Creating Workload Identity Pool (${ENVIRONMENT}) ---"
        gcloud iam workload-identity-pools create "${FULL_POOL_ID}" \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --pool-id="${FULL_POOL_ID}-id" # Appending -id for uniqueness
          --location="global" \
          --display-name="WIF Pool (${ENVIRONMENT}-${POOL_ID_SUFFIX}) (Dry Run)" \
          --dry-run

        echo "--- Dry Run: Creating Workload Identity Pool Provider (${ENVIRONMENT}) ---"
        gcloud iam workload-identity-pools providers create-oidc "${PROVIDER_ID}" \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --location="global" \
          --pool="${FULL_POOL_ID}" \
          --display-name="OIDC Provider (${ENVIRONMENT}-${POOL_ID_SUFFIX}) (Dry Run)" \
          --issuer-uri="${ISSUER_URI}" \
          --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
          --attribute-condition="assertion.attribute_name == 'attribute_value'" \
          --allowed-audiences="your-audience-1,your-audience-2" \
          --dry-run
        echo "Dry run complete."
