name: Test WIF Configuration

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test_wif:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for workload identity federation (if you use it later)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Optional: If not using WIF for this step

    - name: Test Workload Identity Pool Creation (Dry Run)
      run: |
        echo "--- Testing Workload Identity Pool Creation (Dry Run) ---"
        gcloud iam workload-identity-pools create my-workload-identity-pool-test \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --pool-id="my-unique-pool-id-test" \
          --location="global" \
          --display-name="My WIF Pool Test (Dry Run)" \
          --dry-run
        echo "Dry run for Workload Identity Pool creation complete."

    - name: Test Workload Identity Pool Provider Creation (Dry Run)
      run: |
        echo "--- Testing Workload Identity Pool Provider Creation (Dry Run) ---"
        # Ensure the workloadIdentityPool reference is correct
        POOL_ID="my-workload-identity-pool-test"
        PROVIDER_ID="my-oidc-provider-test"
        ISSUER_URI="https://your-oidc-issuer.example.com" # Replace with your actual issuer URI

        gcloud iam workload-identity-pools providers create-oidc "${PROVIDER_ID}" \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --location="global" \
          --pool="${POOL_ID}" \
          --display-name="My OIDC Provider Test (Dry Run)" \
          --issuer-uri="${ISSUER_URI}" \
          --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
          --attribute-condition="assertion.attribute_name == 'attribute_value'" \
          --allowed-audiences="your-audience-1,your-audience-2" \
          --dry-run
        echo "Dry run for Workload Identity Pool Provider creation complete."

    # Optional: Step to actually create (for a more thorough test in a non-prod environment)
    # - name: Apply WIF Configuration (Actual - Use with Caution)
    #   run: |
    #     echo "--- Applying Workload Identity Pool ---"
    #     gcloud iam workload-identity-pools create my-workload-identity-pool-test \
    #       --project="${{ secrets.GCP_PROJECT_ID }}" \
    #       --pool-id="my-unique-pool-id-test" \
    #       --location="global" \
    #       --display-name="My WIF Pool Test"
    #
    #     echo "--- Applying Workload Identity Pool Provider ---"
    #     POOL_ID="my-workload-identity-pool-test"
    #     PROVIDER_ID="my-oidc-provider-test"
    #     ISSUER_URI="https://your-oidc-issuer.example.com" # Replace with your actual issuer URI
    #
    #     gcloud iam workload-identity-pools providers create-oidc "${PROVIDER_ID}" \
    #       --project="${{ secrets.GCP_PROJECT_ID }}" \
    #       --location="global" \
    #       --pool="${POOL_ID}" \
    #       --display-name="My OIDC Provider Test" \
    #       --issuer-uri="${ISSUER_URI}" \
    #       --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
    #       --attribute-condition="assertion.attribute_name == 'attribute_value'" \
    #       --allowed-audiences="your-audience-1,your-audience-2"
    #     echo "WIF configuration applied (for testing)."
