name: Test WIF Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to test in'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod # Use with caution!
      issuer_uri:
        description: 'OIDC Issuer URI'
        required: true
        type: string

jobs:
  test_wif:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Optional

    - name: Test WIF Creation (Dry Run)
      run: |
        echo "Testing in ${{ github.event.inputs.environment }} environment..."
        echo "Using Issuer URI: ${{ github.event.inputs.issuer_uri }}"

        POOL_ID="my-wif-pool-${{ github.event.inputs.environment }}"
        PROVIDER_ID="my-oidc-provider-${{ github.event.inputs.environment }}"

        echo "--- Dry Run: Creating Workload Identity Pool (${{ github.event.inputs.environment }}) ---"
        gcloud iam workload-identity-pools create "${POOL_ID}" \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --pool-id="${POOL_ID}-id" \
          --location="global" \
          --display-name="WIF Pool (${{ github.event.inputs.environment }}) (Dry Run)" \
          --dry-run

        echo "--- Dry Run: Creating Workload Identity Pool Provider (${{ github.event.inputs.environment }}) ---"
        gcloud iam workload-identity-pools providers create-oidc "${PROVIDER_ID}" \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --location="global" \
          --pool="${POOL_ID}" \
          --display-name="OIDC Provider (${{ github.event.inputs.environment }}) (Dry Run)" \
          --issuer-uri="${{ github.event.inputs.issuer_uri }}" \
          --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
          --attribute-condition="assertion.attribute_name == 'attribute_value'" \
          --allowed-audiences="your-audience-1,your-audience-2" \
          --dry-run
        echo "Dry run complete."
