name: Deploy WIF

on:
  # You can choose an event trigger, or manually trigger this workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for workload identity federation from GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Optional: If not using WIF for this step

    - name: Dry Run WIF Configuration
      run: |
        echo "--- Dry Run: Creating Workload Identity Pool ---"
        gcloud iam workload-identity-pools create my-workload-identity-pool \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --pool-id="my-unique-pool-id-dry-run" \
          --location="global" \
          --display-name="My WIF Pool (Dry Run)" \
          --dry-run

        echo "--- Dry Run: Creating Workload Identity Pool Provider ---"
        gcloud iam workload-identity-pools providers create-oidc my-oidc-provider \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --location="global" \
          --pool="my-workload-identity-pool-dry-run" \
          --display-name="My OIDC Provider (Dry Run)" \
          --issuer-uri="https://your-oidc-issuer.example.com" \
          --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
          --attribute-condition="assertion.attribute_name == 'attribute_value'" \
          --allowed-audiences="your-audience-1,your-audience-2" \
          --dry-run
        echo "Dry run complete. Check the output for the planned changes."

    # Optional: Step to actually apply the configuration
    - name: Apply WIF Configuration
      if: github.event_name == 'workflow_dispatch' # Only run when manually triggered (for this example)
      run: |
        echo "--- Creating Workload Identity Pool ---"
        gcloud iam workload-identity-pools create my-workload-identity-pool \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --pool-id="my-unique-pool-id" \
          --location="global" \
          --display-name="My Workload Identity Pool"

        echo "--- Creating Workload Identity Pool Provider ---"
        gcloud iam workload-identity-pools providers create-oidc my-oidc-provider \
          --project="${{ secrets.GCP_PROJECT_ID }}" \
          --location="global" \
          --pool="my-workload-identity-pool" \
          --display-name="My OIDC Provider" \
          --issuer-uri="https://your-oidc-issuer.example.com" \
          --attribute-mapping="google.subject=assertion.sub,attribute.email=assertion.email,attribute.group=assertion.groups" \
          --attribute-condition="assertion.attribute_name == 'attribute_value'" \
          --allowed-audiences="your-audience-1,your-audience-2"
        echo "WIF configuration applied."
