
name: Add Service Account as member to GCP  group
on:
  workflow_dispatch:
    inputs:
      resource_type:
        type: choice
        description: Select the resource
        options:
          - group
      resource_id:
        description: Group ID
        required: true
      service_account:
        description: group email
        required: true
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
jobs:
  Add-Service-Account-as-member-to-GCP-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: "true"
          token_format: access_token
          workload_identity_provider: projects/442242090848/locations/global/workloadIdentityPools/githubaction/providers/saas-resource-management
          service_account: svc-saas-resource-deployer@gcp-koss01.iam.gserviceaccount.com
          access_token_lifetime: 3600s
      - name: Add-Service-Account-as-member-to-GCP-group
        run: >
          if [ "${{ inputs.resource_type }}" == 'Group ID' ]; then

          gcloud identity groups memberships add --group-email="input.group-ID" --member-email="inputs.service_account" --dry-run

          else
            echo "This is an unknown event"
          fi
